- hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker packages
    apt:
      name: "{{ apt_docker_packages }}"
      state: present
      cache_valid_time: 600

  - name: Enable CRI plugin for Kubernetes
    replace:
      dest: /etc/containerd/config.toml
      regexp: '^(disabled_plugins.*)'
      replace: '#\1'

  - name: Enable Docker
    systemd:
      unit: "{{ item }}"
      enabled: yes
      state: restarted
    with_items:
      - docker
      - containerd

  - name: Enable Docker permissions
    user:
      name: hadoop
      append: yes
      groups:
        - docker
