- name: Configure Kubernetes Users
  become: true
  block:
    - name: Create k8s-configs directory
      file:
        path: ~/k8s-configs/
        state: directory
        mode: 0755

    - name: Wait until kube-system is ready
      shell: "kubectl get pods --namespace kube-system --field-selector=status.phase!=Succeeded -o name | xargs -I {} kubectl wait --timeout=900s --namespace kube-system --for=condition=Ready {}"
    
    - name: Waiting for coredns configmap
      shell: 'while ! kubectl get configmap coredns --namespace kube-system; do echo "Waiting for my secret. CTRL-C to exit."; sleep 1; done'
    
    - name: Generate Storage Class Configuration
      become: true
      template:
        src: "k8s-storage-class.yml.j2"
        dest: "~/k8s-configs/k8s-storage-class.yml"

    - name: Create StorageClass
      become: true
      shell: kubectl apply -f ~/k8s-configs/k8s-storage-class.yml

    - name: Generate file with user k8s configuration
      template:
        src: "k8s-user.yml.j2"
        dest: "~/k8s-configs/k8s-user-{{item.username}}.yml"
      with_items: "{{ students }}"
      loop_control:
        label: "{{ item.username }}"

    - name: Applying k8s user configurations
      raw: kubectl apply -f ~/k8s-configs/k8s-user-{{item.username}}.yml
      with_items: "{{ students }}"
      loop_control:
        label: "{{ item.username }}"

    - name: Copy student kubeconfig generation script
      copy:
        src: files/generate-user-k8s-config.sh
        dest: ~/k8s-configs/generate-user-k8s-config.sh
        mode: 0755

    - name: Running kubeconfig generation script for students
      shell: ~/k8s-configs/generate-user-k8s-config.sh {{ item.username }} {{ current_machine_ipaddress }} {{ cluster_name }}
      with_items: "{{ students }}"
      loop_control:
        label: "{{ item.username }}"

    - name: Creating PersistentVolume folders
      file:
        path: /home/{{ item.username }}/{{ pv_basename }}
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
      with_items: "{{ students }}"
      loop_control:
        label: "{{ item.username }}"

    - name: Generate file with user PersistentVolume configuration
      become: true
      template:
        src: "k8s-user-pv.yml.j2"
        dest: "~/k8s-configs/k8s-user-pv-{{item.username}}.yml"
      with_items: "{{ students }}"
      loop_control:
        label: "{{ item.username }}"

    - name: Applying k8s configurations for PersistentVolumes
      become: true
      raw: kubectl apply -f ~/k8s-configs/k8s-user-pv-{{item.username}}.yml
      with_items: "{{ students }}"
      loop_control:
        label: "{{ item.username }}"
