- name: Ensure br_netfilter is enabled.
  modprobe:
    name: br_netfilter
    state: present

- name: Add the br_netfilter module to work across reboot
  shell: |
    echo br_netfilter > /etc/modules-load.d/br_netfilter.conf

- name: Allow bridge traffic through iptables (flannel)
  become: true
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    reload: yes

- name: Disabling swapoff so k8s works correctly
  become: true
  shell: swapoff -a

- name: Add Kubernetes GPG key
  become: true
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key

- name: Add Kubernetes APT repository
  become: true
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /
