- name: Check for existing helm installation
  stat:
    path: "/usr/local/bin/helm"
  register: helm_install
  tags:
    - helm

- name: Check for existing rancher pods
  become: yes
  shell: kubectl -n cattle-system get pods -o name
  ignore_errors: true
  register: rancher_pods
  tags:
    - rancher

- name: Download, install and setup helm environment
  block:
    - name: Start helm installation
      include_tasks: helm.yml
      when: not helm_install.stat.exists
      tags:
        - helm
        - installation

  become: True
  tags:
    - kubernetes
    - installation
    - setup
- name: Rancher Installation
  become_user: "{{ rke_admin_user}}"
  block:
    - name: Wait until cert manager is ready
      shell: kubectl wait --for=condition=ready pod -l app=webhook --timeout=60s -n cert-manager & kubectl wait --for=condition=Established crd certificates.cert-manager.io

    - name: Wait for nginx to be ready
      shell: kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s

    - name: Deploy Rancher Helm
      when: rancher_pods.stdout == ""
      shell: 'helm install rancher rancher-stable/rancher --set hostname={{ rancher_server_name }} --set bootstrapPassword="{{ random_password }}" --namespace cattle-system --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=matheus-alves@ufmg.br'

    - name: Wait until rancher is ready
      shell: "kubectl get pods --namespace cattle-system --field-selector=status.phase!=Succeeded -o name | xargs -I {} kubectl wait --timeout=900s --namespace cattle-system --for=condition=Ready {}"

    - name: Expose Rancher's Ports
      shell: |
        kubectl patch svc rancher -n cattle-system -p '{"spec": {"type": "NodePort","ports": [{"port": 80, "protocol": "TCP", "targetPort": 80, "nodePort": {{ RANCHER_EXPOSED_PORT_HTTP }}}, {"port": 443, "protocol": "TCP", "targetPort": 443, "nodePort": {{ RANCHER_EXPOSED_PORT_HTTPS }} }]}}'

- name: Get Admin Token
  uri:
    method: POST
    status_code: 201
    url: "https://{{ rancher_server_name }}/v3-public/localProviders/local?action=login"
    body_format: json
    headers:
      content-type: application/json
    validate_certs: false
    body:
      username: "admin"
      password: "{{ random_password }}"
      ttl: 60000
  retries: 5
  delay: 5
  register: token

- name: Create Users in Rancher
  include_tasks: create-rancher-users.yml
  vars:
    access_token: "{{ token.json }}"
    kind: "{{ student_kind }}"
  loop: "{{ students }}"
  loop_control:
    loop_var: user

- name: Create Admins in Rancher
  include_tasks: create-rancher-users.yml
  vars:
    access_token: "{{ token.json }}"
    kind: "{{ admin_kind }}"
  loop: "{{ admins }}"
  loop_control:
    loop_var: user
